module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-deep': '#0B0C10',
        'surface': '#121317',
        'surface-dim': '#121317',
        'surface-elevated': '#1A1B23',
        'surface-glass': 'rgba(26, 27, 35, 0.6)',
        'surface-container': '#1f1f24',
        'surface-container-low': '#1a1b20',
        'surface-container-high': '#292a2e',
        'surface-bright': '#38393e',
        'border-subtle': '#2E3039',
        'text-dim': '#9499AD',
        'on-surface': '#e3e2e8',
        'on-surface-variant': '#c4c5d9',
        'outline': '#8e90a2',
        'outline-variant': '#434656',
        'primary': '#b8c3ff',
        'on-primary': '#002387',
        'primary-container': '#2d5bff',
        'on-primary-container': '#efefff',
        'secondary': '#e0b6ff',
        'on-secondary': '#4c007d',
        'secondary-container': '#6d11ad',
        'tertiary': '#00dce5',
        'on-tertiary-container': '#bafbff',
        'error': '#ffb4ab',
        'inverse-surface': '#e3e2e8',
        'inverse-on-surface': '#2f3035',
      },
      fontFamily: {
        'geist': ['Geist', 'Inter', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl':  ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg':  ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md':  ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg':      ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':      ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps':   ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'code-sm':      ['14px', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        'section-gap-lg': '120px',
        'section-gap-md': '80px',
        'card-padding':   '32px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'stack-sm':       '8px',
        'stack-md':       '16px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      backdropBlur: {
        'glass': '20px',
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
};
